markdown: kramdown

gems:
  - jekyll-sitemap

nav:
  Home: //g14n.info/SQL92-JSON
  Code: https://github.com/fibo/SQL92-JSON

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: common/page
